version: '3.9'

services:
  backend:
    image: backend
    container_name: backend_service
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    env_file:
      - .env
    command: gunicorn flexicart.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/media
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: flexicart
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx_service
      dockerfile: Dockerfile
    container_name: nginx_service
    volumes:
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/media
    restart: always
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres-data:
  static_volume:
  media_volume:
