version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    volumes:
        - .:/app
    depends_on:
      - db

  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=DATABASE_NAME
      - POSTGRES_USER=DATABASE_USER
      - POSTGRES_PASSWORD=DATABASE_PASSWORD
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"