# Generated by Django 5.0.1 on 2024-07-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0002_parentcategory_slug_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_type',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('BUY_ONE_GET_ONE', 'Buy One Get One'), ('BUY_TWO_GET_ONE', 'Buy Two Get One')], default='DISCOUNT', max_length=255),
        ),
    ]
