# Generated by Django 5.0.1 on 2024-02-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('PRICE', 'Price'), ('BUY_ONE_GET_ONE', 'Buy One Get One'), ('BUY_TWO_GET_ONE', 'Buy Two Get One')], default='PERCENTAGE', max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_service.product')),
            ],
        ),
    ]
