# Generated by Django 5.0.1 on 2024-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>/'),
        ),
    ]
