# Generated by Django 5.0.1 on 2024-01-13 16:49

import django.db.models.deletion
import product_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0002_product_image_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_service.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product_service.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=product_service.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=product_service.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=product_service.models.product_image_path),
        ),
    ]
